<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rules\Password;

// @generated by server-setup-toolkit laravel-deployment generic-admin-create
class CreateAdminUser extends Command
{
    protected $signature = 'admin:create
                            {--name= : Admin display name}
                            {--email= : Admin email address}
                            {--role= : Admin role}
                            {--password= : Password; interactive prompt is preferred}
                            {--update : Update an existing user instead of failing}
                            {--force : Skip confirmation for non-interactive use}';

    protected $description = 'Create a central application admin account';

    private const MODEL_CLASS = 'App\Models\User';

    private const NAME_COLUMN = 'name';

    private const EMAIL_COLUMN = 'email';

    private const PASSWORD_COLUMN = 'password';

    private const ROLE_COLUMN = 'role';

    private const ACTIVE_COLUMN = 'active';

    private const EMAIL_VERIFIED_COLUMN = 'email_verified_at';

    private const DEFAULT_ROLE = 'superadmin';

    private const DEFAULT_ACTIVE = true;

    public function handle(): int
    {
        $modelClass = self::MODEL_CLASS;

        if (! class_exists($modelClass) || ! is_subclass_of($modelClass, Model::class)) {
            $this->error("Configured admin model [{$modelClass}] is not an Eloquent model.");

            return self::FAILURE;
        }

        $name = trim((string) ($this->option('name') ?: $this->ask('Admin name')));
        $email = strtolower(trim((string) ($this->option('email') ?: $this->ask('Admin email'))));
        $role = trim((string) ($this->option('role') ?: self::DEFAULT_ROLE));
        $password = (string) ($this->option('password') ?: $this->secret('Admin password'));

        if ($this->option('password') === null) {
            $confirmation = (string) $this->secret('Confirm admin password');
            if (! hash_equals($password, $confirmation)) {
                $this->error('Password confirmation does not match.');

                return self::FAILURE;
            }
        }

        $validator = Validator::make([
            'name' => $name,
            'email' => $email,
            'role' => $role,
            'password' => $password,
        ], [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'email:rfc', 'max:255'],
            'role' => ['required', 'string', 'max:64', 'regex:/^[A-Za-z0-9_.:-]+$/'],
            'password' => ['required', 'string', Password::min(12)->mixedCase()->numbers()->symbols()],
        ]);

        if ($validator->fails()) {
            foreach ($validator->errors()->all() as $error) {
                $this->error($error);
            }

            return self::FAILURE;
        }

        if (! $this->emailIsAllowed($email)) {
            $this->error("Email [{$email}] is not allowed by ADMIN_EMAIL_WHITELIST.");

            return self::FAILURE;
        }

        /** @var Model|null $existing */
        $existing = $modelClass::query()->where(self::EMAIL_COLUMN, $email)->first();
        if ($existing && ! $this->option('update')) {
            $this->error("A user with email [{$email}] already exists. Re-run with --update to update it.");

            return self::FAILURE;
        }

        $action = $existing ? 'update' : 'create';
        if (! $this->option('force')) {
            $this->line('');
            $this->line(ucfirst($action).' admin account:');
            $this->line("Name: {$name}");
            $this->line("Email: {$email}");
            $this->line("Role: {$role}");
            if (! $this->confirm('Continue?', true)) {
                $this->warn('No changes made.');

                return self::SUCCESS;
            }
        }

        $attributes = [
            self::NAME_COLUMN => $name,
            self::EMAIL_COLUMN => $email,
            self::PASSWORD_COLUMN => Hash::make($password),
        ];

        if (self::ROLE_COLUMN !== '') {
            $attributes[self::ROLE_COLUMN] = $role;
        }

        if (self::ACTIVE_COLUMN !== '') {
            $attributes[self::ACTIVE_COLUMN] = self::DEFAULT_ACTIVE;
        }

        if (self::EMAIL_VERIFIED_COLUMN !== '') {
            $attributes[self::EMAIL_VERIFIED_COLUMN] = now();
        }

        try {
            if ($existing) {
                $existing->forceFill($attributes)->save();
                $this->info("Admin account updated: {$email}");

                return self::SUCCESS;
            }

            /** @var Model $user */
            $user = new $modelClass;
            $user->forceFill($attributes)->save();
            $this->info("Admin account created: {$email}");

            return self::SUCCESS;
        } catch (\Throwable $exception) {
            report($exception);
            $this->error('Admin account creation failed: '.$exception->getMessage());

            return self::FAILURE;
        }
    }

    private function emailIsAllowed(string $email): bool
    {
        $whitelist = trim((string) env('ADMIN_EMAIL_WHITELIST', ''));
        if ($whitelist === '') {
            return true;
        }

        foreach (explode(',', $whitelist) as $pattern) {
            $pattern = trim($pattern);
            if ($pattern === '') {
                continue;
            }

            $regex = '/^'.str_replace('\\*', '.*', preg_quote(strtolower($pattern), '/')).'$/';
            if (preg_match($regex, strtolower($email)) === 1) {
                return true;
            }
        }

        return false;
    }
}
